[package]
name = "playerone-sdk-sys"
version = "0.1.1"
edition = "2021"
description = "PlayerOne SDK bindings"
license = "MIT"
repository = "https://github.com/Uriopass/playerone-sdk-rs"

[dependencies]

[build-dependencies]
bindgen = "0.71.1"