[package]
name = "playerone-sdk-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
libusb-sys = { version = "0.2.3" }
libloading = "0.8.5"
lazy_static = "1.5.0"

[build-dependencies]
bindgen = "0.70.1"